apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: mymount
      mountPath: /tmp
  volumes:
  - name: mymount
    persistentVolumeClaim:
      claimName: mymount